# Autogenerated by `bun2nix`, editing manually is not recommended
#
# Set of Bun packages to install
#
# Consume this with `fetchBunDeps` (recommended)
# or `pkgs.callPackage` if you wish to handle
# it manually.
{
  copyPathToStore,
  fetchFromGitHub,
  fetchgit,
  fetchurl,
  ...
}:
{
  "@pkmn/sets@5.2.0" = fetchurl {
    url = "https://registry.npmjs.org/@pkmn/sets/-/sets-5.2.0.tgz";
    hash = "sha512-WHAW6bZu0WCo/3b+LTW7BE0fBhYZnWH1lCXIu2an8/wTiZ/+s1eTcQYj7W/YQKxWT5dm/La03AZ6CeqdJip9CQ==";
  };
  "@pkmn/sim@0.10.8" = fetchurl {
    url = "https://registry.npmjs.org/@pkmn/sim/-/sim-0.10.8.tgz";
    hash = "sha512-FoRb5S3VWnOzQcSEbkalVqgECKX1DUo/RoFS6Et4taYsI6pcSdEYmvtPmRMbGnex3JRAATbkgmbyh8ErSmJsYQ==";
  };
  "@pkmn/streams@1.1.0" = fetchurl {
    url = "https://registry.npmjs.org/@pkmn/streams/-/streams-1.1.0.tgz";
    hash = "sha512-Pp9k7gt4xd76DqTU+LQEUyzuaauM4bV1MlehVtX1NS7o9zMFtjw50MfaEQ62dIMZyzxNjsJGoLGBeY1iSYLsRA==";
  };
  "@pkmn/types@4.0.0" = fetchurl {
    url = "https://registry.npmjs.org/@pkmn/types/-/types-4.0.0.tgz";
    hash = "sha512-gR2s/pxJYEegek1TtsYCQupNR3d5hMlcJFsiD+2LyfKr4tc+gETTql47tWLX5mFSbPcbXh7f4+7txlMIDoZx/g==";
  };
  "@types/node@25.7.0" = fetchurl {
    url = "https://registry.npmjs.org/@types/node/-/node-25.7.0.tgz";
    hash = "sha512-z+pdZyxE+RTQE9AcboAZCb4otwcrvgHD+GlBpPgn0emDVt0ohrTMhAwlr2Wd9nZ+nihhYFxO2pThz3C5qSu2Eg==";
  };
  "bun2nix@2.1.0" = fetchurl {
    url = "https://registry.npmjs.org/bun2nix/-/bun2nix-2.1.0.tgz";
    hash = "sha512-EzVw2dp24nPFuJYc6IZaKyfsmQiL//GrNfy6GgvFc/3l3guBwy9O2FgEBDIOwpQ61jq2jO9gPjYHrbHPev1rqg==";
  };
  "mri@1.2.0" = fetchurl {
    url = "https://registry.npmjs.org/mri/-/mri-1.2.0.tgz";
    hash = "sha512-tzzskb3bG8LvYGFF/mDTpq3jpI6Q9wc3LEmBaghu+DdCssd1FakN7Bc0hVNmEyGq1bq3RgfkCb3cmQLpNPOroA==";
  };
  "sade@1.8.1" = fetchurl {
    url = "https://registry.npmjs.org/sade/-/sade-1.8.1.tgz";
    hash = "sha512-xal3CZX1Xlo/k4ApwCFrHVACi9fBqJ7V+mwhBsuf/1IOKbBy098Fex+Wa/5QMubw09pSZ/u8EY8PWgevJsXp1A==";
  };
  "ts-chacha20@1.2.0" = fetchurl {
    url = "https://registry.npmjs.org/ts-chacha20/-/ts-chacha20-1.2.0.tgz";
    hash = "sha512-PTyPoWYHc2we8P2NTn5hpYG211popWbkjiw+k63xqjeMrx9pPtXSclz9F3fu0Tpr+vfR1xxcQFwsEkh1cXMLqw==";
  };
  "typescript@6.0.3" = fetchurl {
    url = "https://registry.npmjs.org/typescript/-/typescript-6.0.3.tgz";
    hash = "sha512-y2TvuxSZPDyQakkFRPZHKFm+KKVqIisdg9/CZwm9ftvKXLP8NRWj38/ODjNbr43SsoXqNuAisEf1GdCxqWcdBw==";
  };
  "undici-types@7.21.0" = fetchurl {
    url = "https://registry.npmjs.org/undici-types/-/undici-types-7.21.0.tgz";
    hash = "sha512-w9IMgQrz4O0YN1LtB7K5P63vhlIOvC7opSmouCJ+ZywlPAlO9gIkJ+otk6LvGpAs2wg4econaCz3TvQ9xPoyuQ==";
  };
}
